language: node_js

node_js:
  - "5.1"

addons:
  sauce_connect: true
  # Node 5 requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    - CXX=g++-4.8 # This is linked to the issue above with Node 5

before_install:
  - sudo apt-get update
  - sudo apt-get install libxss1 libappindicator1 libindicator7 fonts-liberation
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g tsd
  - npm install -g gulp
  - npm install -g karma
  - npm install -g protractor
  - npm install -g typings

before_script:
  - rm -rf node_modules/
  - webdriver-manager update
  - npm install
  - typings install

script:
  - gulp test